### ISSUE TITLE
Setting: Twitter OGP

### ISSUE THREAD

**Issue by yamanoku** [vue-a11y/vue-a11y.com#36]
I want to create a Twitter card (OGP) because it doesn't show up when I publish on Twitter.

[![Image from Gyazo](https://i.gyazo.com/ccfb5a324e77c6739fdec85f46e25ae1.png)](https://gyazo.com/ccfb5a324e77c6739fdec85f46e25ae1)

**Comment by ktquez** [comment]
I did a test on this site https://cards-dev.twitter.com/validator

INFO:  Page fetched successfully ✔️
INFO:  26 metatags were found ✔️
INFO:  twitter:card = summary_large_image tag found ✔️
ERROR: Possibly invalid value (if specified) (**twitter:title**) ❌
ERROR: Possibly invalid value (if specified) (**og:title**) ❌
ERROR: Possibly invalid value (if specified) (**twitter:text:title**) ❌

I think we need to add the missing meta tags.

**Comment by ktquez** [comment]
I translated the share image, if you want you can add it to yaml from [index /jp](https://github.com/vue-a11y/vue-a11y.com/blob/master/src/jp/index.md)

```
meta:
  - name: 'twitter:image'
    content: '/img/social-share-jp.png'
```

![social-share - jp](https://user-images.githubusercontent.com/8084606/105118175-a986f180-5aac-11eb-8c49-8b93a306855a.png)

**Comment by yamanoku** [comment]
Use it ?
https://github.com/lorisleiva/vuepress-plugin-seo

**Comment by ktquez** [comment]
@yamanoku 
https://vuepress.vuejs.org/guide/frontmatter.html#meta
