### ISSUE TITLE
Project Page Firefox Android

### ISSUE THREAD

**Issue by plfstr** [vue-a11y/vue-a11y.com#57]
I can not read page https://vue-a11y.com/project/ in Firefox, Android.

Something triggers beyond the introduction section and bounces the browser view back to the top of the page.

**Comment by ktquez** [comment]
Thanks @plfstr 

I will check!

**Comment by JoostKersjes** [comment]
Did a quick test, and I cannot reproduce this error.

https://gfycat.com/nauticalabandonedbarnswallow
