### ISSUE TITLE
Vue Announcer Post Paragraph

### ISSUE THREAD

**Issue by plfstr** [vue-a11y/vue-a11y.com#58]
https://vue-a11y.com/posts/vue-announcer/#the-problem-of-asynchronous-updates

I had trouble understanding part of the the post: 
> Parts of the doucment could and will get updated, added and removed. All of this in an elegant, smooth and asynchronous way, to delivery that reactive, "app-y" experience – but without a page reload. Alas, this causes a problem for screen reader users.

This particular paragraph is difficult to read. 
* Spelling, *doucment 
* Odd phrasing, *to delivery
* Missing word or punctuation in a complex sentence

See my edited attempt:
> Parts of the document could and will get updated, added and removed. All of this happens in an elegant, smooth and asynchronous way - to deliver that reactive, "app-y" experience – without a page reload. Alas, this causes a problem for screen reader users.

**Comment by ktquez** [comment]
Hi @plfstr 

We would appreciate receiving a PR from you with these corrections.
